import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import 'chart.js';
//import {BrowserModule} from '@angular/platform-browser';
//import {BrowserAnimationsModule} from '@angular/platform-browser/animations';

import {
  AccordionModule,
  BlockUIModule,
  ButtonModule,
  CalendarModule,
  CaptchaModule,
  ChartModule,
  CheckboxModule,
  ConfirmationService,
  ConfirmDialogModule,
  ContextMenuModule,
  DataGridModule,
  DataListModule,
  DataScrollerModule,
  DataTableModule,
  DeferModule,
  DialogModule,
  DragDropModule,
  DropdownModule,
  EditorModule,
  FieldsetModule,
  GalleriaModule,
  GMapModule,
  GrowlModule,
  InplaceModule,
  InputMaskModule,
  InputSwitchModule,
  InputTextareaModule,
  InputTextModule,
  ListboxModule,
  MenubarModule,
  MenuModule,
  MessagesModule,
  MultiSelectModule,
  PanelModule,
  RadioButtonModule,
  RatingModule,
  ScheduleModule,
  SelectButtonModule,
  SharedModule,
  SliderModule,
  SpinnerModule,
  SplitButtonModule,
  StepsModule,
  TabMenuModule,
  TabViewModule,
  ToggleButtonModule,
  TooltipModule,
  TreeModule,
  TriStateCheckboxModule,
  } from 'primeng/primeng';


@NgModule({
  imports: [
    AccordionModule,
    BlockUIModule,
    ButtonModule,
    CalendarModule,
    CaptchaModule,
    ChartModule,
    CheckboxModule,
    ConfirmDialogModule,
    ContextMenuModule,
    DataGridModule,
    DataListModule,
    DataScrollerModule,
    DataTableModule,
    DeferModule,
    DialogModule,
    DragDropModule,
    DropdownModule,
    EditorModule,
    FieldsetModule,
    GalleriaModule,
    GMapModule,
    GrowlModule,
    InplaceModule,
    InputMaskModule,
    InputSwitchModule,
    InputTextareaModule,
    InputTextModule,
    ListboxModule,
    MenubarModule,
    MenuModule,
    MessagesModule,
    MultiSelectModule,
    PanelModule,
    RadioButtonModule,
    RatingModule,
    ScheduleModule,
    SelectButtonModule,
    SharedModule,
    SliderModule,
    SpinnerModule,
    SplitButtonModule,
    StepsModule,
    TabMenuModule,
    TabViewModule,
    ToggleButtonModule,
    TooltipModule,
    TreeModule,
    TriStateCheckboxModule,
  ],
  exports: [
    AccordionModule,
    BlockUIModule,
    ButtonModule,
    CalendarModule,
    CaptchaModule,
    ChartModule,
    CheckboxModule,
    ConfirmDialogModule,
    ContextMenuModule,
    DataGridModule,
    DataListModule,
    DataScrollerModule,
    DataTableModule,
    DeferModule,
    DialogModule,
    DragDropModule,
    DropdownModule,
    EditorModule,
    FieldsetModule,
    GalleriaModule,
    GMapModule,
    GrowlModule,
    InplaceModule,
    InputMaskModule,
    InputSwitchModule,
    InputTextareaModule,
    InputTextModule,
    ListboxModule,
    MenubarModule,
    MenuModule,
    MessagesModule,
    MultiSelectModule,
    PanelModule,
    RadioButtonModule,
    RatingModule,
    ScheduleModule,
    SelectButtonModule,
    SharedModule,
    SliderModule,
    SpinnerModule,
    SplitButtonModule,
    StepsModule,
    TabMenuModule,
    TabViewModule,
    ToggleButtonModule,
    TooltipModule,
    TreeModule,
    TriStateCheckboxModule,
    ],
    providers: [ ConfirmationService ]
})


export class PrimeNGModule { }
